EmptyLinesAroundModuleBody:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

LineLength:
  Max: 120

ClassLength:
  Enabled: true
  CountComments: false
  Max: 150

MethodLength:
  Enabled: false

WhileUntilModifier:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false
